---
title: "Graphics with ggplot2"
author: "Julie"
date: "11/21/2017"
output: html_document
---

# Learning ggplot2

Load tidyverse
```{r tidyverse}
library(tidyverse)
```


We're learning ggplot2 It's going to be amazing. 


```{r data}

ohi_data <- read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/OHI_global_data.csv")

```

```{r analysis} 

head(ohi_data)

summary(ohi_data)

table(ohi_data$georegion_one)

table(ohi_data$georegion_two)
```


```{r plot}

ggplot(data = ohi_data, aes(x = OHI_score, y = HDI))

ggplot(data = ohi_data, aes(x = georegion_one, y =OHI_score)) + 
  geom_point()

ggplot(data = ohi_data, aes(x = georegion_one, y =OHI_score)) + 
  geom_jitter(width=0.2) # the width argument describes how much scatter to add

ggplot(data = ohi_data, aes(x = georegion_one)) + 
  geom_bar() 

ggplot(data = ohi_data, aes(x = HDI)) + 
  geom_histogram() 
```

```{r more_data} 

ohi_summary <- read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/OHI_scores_georegion_summary.csv")

ohi_summary
```

```{r plot_more_data}

ggplot(data = ohi_summary, aes(x = georegions, y = OHI_score_average)) + 
  geom_bar(stat="identity") +
  geom_jitter(data=ohi_data, aes(x=georegion_one, y=OHI_score))

```

